spring:
  application:
    name: salemale
  
  # # 관리자 계정 (환경변수)
  # security:
  #   user:
  #     name: ${ADMIN_USERNAME}
  #     password: ${ADMIN_PASSWORD}
  
  # PostgreSQL 데이터베이스
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway 마이그레이션 설정
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  
  # Gmail SMTP 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_APP_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  
  # Redis 설정 (하드코딩)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# 로그 설정
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Actuator 설정 (health, info 노출)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# JWT 설정: jjwt에서 사용할 비밀키와 만료시간(ms)
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

# 비밀번호 재설정 토큰 설정
password:
  reset:
    token-validity: 30  # 토큰 유효 시간(분)
