spring:
  application:
    name: salemale
  
  # 관리자 계정 (환경변수)
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  
  # PostgreSQL 데이터베이스
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # 로그 설정
  logging:
    level:
      org.hibernate.SQL: INFO
      org.hibernate.type.descriptor.sql: TRACE

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
